/* DO NOT EDIT THIS FILE - it is machine generated */
#include "jni.h"
#include "jni_md.h"
#include <map>
/* Header for class dll_DataManger */

#ifndef _Included_dll_DataManger
#define _Included_dll_DataManger
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     dll_DataManger
 * Method:    getValueByKey
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_dll_DataManger_getValueByKey
  (JNIEnv *, jobject, jstring);

/*
 * Class:     dll_DataManger
 * Method:    getMapSize
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_dll_DataManger_getMapSize
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
